events {}
stream {
    upstream tor_proxies {
        random;
        server onion_circuit_1:9050;
        server onion_circuit_2:9050;
        server onion_circuit_3:9050;
    }
    server {
        listen 9050;
        proxy_pass tor_proxies;
        proxy_connect_timeout 5s;
    }
}
